//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnitApp.RealTimeDriverService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RealTimeDriverService.IRealTimeDriver")]
    public interface IRealTimeDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/InitRealTimeUnit", ReplyAction="http://tempuri.org/IRealTimeDriver/InitRealTimeUnitResponse")]
        bool InitRealTimeUnit(string rtuId, string path, string rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/InitRealTimeUnit", ReplyAction="http://tempuri.org/IRealTimeDriver/InitRealTimeUnitResponse")]
        System.Threading.Tasks.Task<bool> InitRealTimeUnitAsync(string rtuId, string path, string rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/WriteValue", ReplyAction="http://tempuri.org/IRealTimeDriver/WriteValueResponse")]
        void WriteValue(string rtuId, string value, string rtuAddress, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/WriteValue", ReplyAction="http://tempuri.org/IRealTimeDriver/WriteValueResponse")]
        System.Threading.Tasks.Task WriteValueAsync(string rtuId, string value, string rtuAddress, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeDriverChannel : RealTimeUnitApp.RealTimeDriverService.IRealTimeDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDriverClient : System.ServiceModel.ClientBase<RealTimeUnitApp.RealTimeDriverService.IRealTimeDriver>, RealTimeUnitApp.RealTimeDriverService.IRealTimeDriver {
        
        public RealTimeDriverClient() {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InitRealTimeUnit(string rtuId, string path, string rtuAddress) {
            return base.Channel.InitRealTimeUnit(rtuId, path, rtuAddress);
        }
        
        public System.Threading.Tasks.Task<bool> InitRealTimeUnitAsync(string rtuId, string path, string rtuAddress) {
            return base.Channel.InitRealTimeUnitAsync(rtuId, path, rtuAddress);
        }
        
        public void WriteValue(string rtuId, string value, string rtuAddress, byte[] signature) {
            base.Channel.WriteValue(rtuId, value, rtuAddress, signature);
        }
        
        public System.Threading.Tasks.Task WriteValueAsync(string rtuId, string value, string rtuAddress, byte[] signature) {
            return base.Channel.WriteValueAsync(rtuId, value, rtuAddress, signature);
        }
    }
}
